const collectionData = {
  1: { name: "Golden Gate Bridge", location: "San Francisco, United States 🇺🇲", image: "image/level1.png" },
  2: { name: "Statue of Liberty", location: "New York City, United States 🇺🇲", image: "image/level2.png" },
  3: { name: "Colosseum", location: "Rome, Italy 🇮🇹", image: "image/level3.png" },
  4: { name: "Leaning Tower of Pisa", location: "Pisa, Italy 🇮🇹", image: "image/level4.png" },
  5: { name: "Stonehenge", location: "Amesbury, United Kingdom 🇬🇧", image: "image/level5.png" },
  6: { name: "Eifel Tower", location: "Paris, France 🇫🇷", image: "image/level6.png" },
  7: { name: "Pyramid of Giza", location: "Giza, Egypt 🇪🇬", image: "image/level7.png" },
  8: { name: "Chocolate Hills", location: "Carmen, Bohol, Philippines 🇵🇭", image: "image/level8.png" },
  9: { name: "Great Wall of China", location: "Beijing, China 🇨🇳", image: "image/level9.png" },
  10: { name: "Tower Bridge", location: "London, United Kingdom 🇬🇧", image: "image/level10.png" },
  11: { name: "Mount Rushmore", location: "Keystone, United States 🇺🇲", image: "image/level11.png" },
  12: { name: "Mount Fuji", location: "Fujikawaguchiko, Japan 🇯🇵", image: "image/level12.png" },
  13: { name: "Philippine Rice Terraces", location: "Banaue, Ifugao, Philippines 🇵🇭", image: "image/level13.png" },
  14: { name: "Mount Everest", location: "Khumjung / Solukhumbu, Nepal 🇳🇵", image: "image/level14.png" },
  15: { name: "Matterhorn", location: "Zermatt, Switzerland 🇨🇭", image: "image/level15.png" },
  16: { name: "Denali", location: "Denali Area, United States 🇺🇲 ", image: "image/level16.png" },
  17: { name: "Mount Kilimanjaro", location: "Moshi, Tanzania 🇹🇿", image: "image/level17.png" },
  18: { name: "Aconcagua", location: "Mendoza, Argentina 🇦🇷", image: "image/level18.png" },
  19: { name: "Mount Elbrus", location: "Kabardino-Balkaria, Russia 🇷🇺", image: "image/level19.png" },
  20: { name: "Table Mountain", location: "Cape Town, South Africa 🇿🇦", image: "image/level20.png" },
  21: { name: "Saint Peter's Basilica", location: "Vatican City 🇻🇦", image: "image/level21.png" },
  22: { name: "Notre-Dame de Paris", location: "Paris, France 🇫🇷", image: "image/level22.png" },
  23: { name: "Sagrada Familia", location: "Barcelpna, Spain 🇪🇸", image: "image/level23.png" },
  24: { name: "Saint Mark Basilica", location: "Venice, Italy 🇮🇹", image: "image/level24.png" },
  25: { name: "Basilica of the Sacred Heart (Sacre-Cœur)", location: "Paris, France 🇫🇷", image: "image/level25.png" },
  26: { name: "Westminster Abbey", location: "London, United Kingdom 🇬🇧", image: "image/level26.png" },
  27: { name: "Duomo di Milano (Milan Cathedral)", location: "Milan, Italy 🇮🇹", image: "image/level27.png" },
  28: { name: "Church of the Holy Sepulchre", location: "Jerusalem, Isrsel 🇮🇱", image: "image/level28.png" },
  29: { name: "Basilica of Our Lady of Guadalupe", location: "Mexico City, Mexico 🇲🇽", image: "image/level29.png" },
  30: { name: "Hagia Sophia", location: "Istanbul, Turkey 🇹🇷", image: "image/level30.png" },
  31: { name: "Middlemist's Red", location: "Native Origin: China 🇨🇳", image: "image/level31.png" },
  32: { name: "Ghost Orchid", location: "Native Origin: Florida 🇺🇲, Cuba 🇨🇺 & the Bahamas 🇧🇸", image: "image/level32.png" },
  33: { name: "Kadupul Flower", location: " Native Origin: Sri Lanka 🇱🇰", image: "image/level33.png" },
  34: { name: "Jade Vine", location: " Native Origin: Philippines 🇵🇭", image: "image/level34.png" },
  35: { name: "Chocolate Cosmos", location: "Native Origin: Mexico 🇲🇽", image: "image/level35.png" },
  36: { name: "Franklin Tree Flower", location: "Native Origin: Georgia, United States 🇺🇲", image: "image/level36.png" },
  37: { name: "Corpse Flower", location: "Native Origin: Indonesia 🇮🇩", image: "image/level37.png" },
  38: { name: "Rothschild's Slipper Orchid", location: "Native Origin: Borneo, Malaysia 🇲🇾", image: "image/level38.png" },
  39: { name: "Juliet Rose", location:"Native Origin: United Kingdom 🇬🇧", image: "image/level39.png" },
  40: { name: "Fire Lily", location: "Native Origin: Native to Africa and tropical Asia", image: "image/level40.png" },
  41: { name: "", location: "", image: "image/level41.png" },
  42: { name: "", location: "", image: "image/level42.png" },
  43: { name: "", location: "", image: "image/level43.png" },
  44: { name: "", location: "", image: "image/level44.png" },
  45: { name: "", location: "", image: "image/level45.png" },
  46: { name: "", location: "", image: "image/level46.png" },
  47: { name: "", location: "", image: "image/level47.png" },
  48: { name: "", location: "", image: "image/level48.png" },
  49: { name: "", location: "", image: "image/level49.png" },
  50: { name: "", location: "", image: "image/level50.png" },
  51: { name: "", location: "", image: "image/level51.png" },
  52: { name: "", location: "", image: "image/level52.png" },
  53: { name: "", location: "", image: "image/level53.png" },
  54: { name: "", location: "", image: "image/level54.png" },
  55: { name: "", location: "", image: "image/level55.png" },
  56: { name: "", location: "", image: "image/level56.png" },
  57: { name: "", location: "", image: "image/level57.png" },
  58: { name: "", location: "", image: "image/level58.png" },
  59: { name: "", location: "", image: "image/level59.png" },
  60: { name: "", location: "", image: "image/level60.png" },
  61: { name: "", location: "", image: "image/level61.png" },
  62: { name: "", location: "", image: "image/level62.png" },
  63: { name: "", location: "", image: "image/level63.png" },
  64: { name: "", location: "", image: "image/level64.png" },
  65: { name: "", location: "", image: "image/level65.png" },
  66: { name: "", location: "", image: "image/level66.png" },
  67: { name: "", location: "", image: "image/level67.png" },
  68: { name: "", location: "", image: "image/level68.png" },
  69: { name: "", location: "", image: "image/level69.png" },
  70: { name: "", location: "", image: "image/level70.png" },
  71: { name: "", location: "", image: "image/level71.png" },
  72: { name: "", location: "", image: "image/level72.png" },
  73: { name: "", location: "", image: "image/level73.png" },
  74: { name: "", location: "", image: "image/level74.png" },
  75: { name: "", location: "", image: "image/level75.png" },
  76: { name: "", location: "", image: "image/level76.png" },
  77: { name: "", location: "", image: "image/level77.png" },
  78: { name: "", location: "", image: "image/level78.png" },
  79: { name: "", location: "", image: "image/level79.png" },
  80: { name: "", location: "", image: "image/level80.png" },
  81: { name: "", location: "", image: "image/level81.png" },
  82: { name: "", location: "", image: "image/level82.png" },
  83: { name: "", location: "", image: "image/level83.png" },
  84: { name: "", location: "", image: "image/level84.png" },
  85: { name: "", location: "", image: "image/level85.png" },
  86: { name: "", location: "", image: "image/level86.png" },
  87: { name: "", location: "", image: "image/level87.png" },
  88: { name: "", location: "", image: "image/level88.png" },
  89: { name: "", location: "", image: "image/level89.png" },
  90: { name: "", location: "", image: "image/level90.png" },
  91: { name: "", location: "", image: "image/level91.png" },
  92: { name: "", location: "", image: "image/level92.png" },
  93: { name: "", location: "", image: "image/level93.png" },
  94: { name: "", location: "", image: "image/level94.png" },
  95: { name: "", location: "", image: "image/level95.png" },
  96: { name: "", location: "", image: "image/level96.png" },
  97: { name: "", location: "", image: "image/level97.png" },
  98: { name: "", location: "", image: "image/level98.png" },
  99: { name: "", location: "", image: "image/level99.png" },
  100: { name: "", location: "", image: "image/level100.png" },
  101: { name: "", location: "", image: "image/level101.png" },
  102: { name: "", location: "", image: "image/level102.png" },
  103: { name: "", location: "", image: "image/level103.png" },
  104: { name: "", location: "", image: "image/level104.png" },
  105: { name: "", location: "", image: "image/level105.png" },
  106: { name: "", location: "", image: "image/level106.png" },
  107: { name: "", location: "", image: "image/level107.png" },
  108: { name: "", location: "", image: "image/level108.png" },
  109: { name: "", location: "", image: "image/level109.png" },
  110: { name: "", location: "", image: "image/level110.png" },
  111: { name: "", location: "", image: "image/level111.png" },
  112: { name: "", location: "", image: "image/level112.png" },
  113: { name: "", location: "", image: "image/level113.png" },
  114: { name: "", location: "", image: "image/level114.png" },
  115: { name: "", location: "", image: "image/level115.png" },
  116: { name: "", location: "", image: "image/level116.png" },
  117: { name: "", location: "", image: "image/level117.png" },
  118: { name: "", location: "", image: "image/level118.png" },
  119: { name: "", location: "", image: "image/level119.png" },
  120: { name: "", location: "", image: "image/level120.png" },
  121: { name: "", location: "", image: "image/level121.png" },
  122: { name: "", location: "", image: "image/level122.png" },
  123: { name: "", location: "", image: "image/level123.png" },
  124: { name: "", location: "", image: "image/level124.png" },
  125: { name: "", location: "", image: "image/level125.png" },
  126: { name: "", location: "", image: "image/level126.png" },
  127: { name: "", location: "", image: "image/level127.png" },
  128: { name: "", location: "", image: "image/level128.png" },
  129: { name: "", location: "", image: "image/level129.png" },
  130: { name: "", location: "", image: "image/level130.png" },
  131: { name: "", location: "", image: "image/level131.png" },
  132: { name: "", location: "", image: "image/level132.png" },
  133: { name: "", location: "", image: "image/level133.png" },
  134: { name: "", location: "", image: "image/level134.png" },
  135: { name: "", location: "", image: "image/level135.png" },
  136: { name: "", location: "", image: "image/level136.png" },
  137: { name: "", location: "", image: "image/level137.png" },
  138: { name: "", location: "", image: "image/level138.png" },
  139: { name: "", location: "", image: "image/level139.png" },
  140: { name: "", location: "", image: "image/level140.png" },
  141: { name: "", location: "", image: "image/level141.png" },
  142: { name: "", location: "", image: "image/level142.png" },
  143: { name: "", location: "", image: "image/level143.png" },
  144: { name: "", location: "", image: "image/level144.png" },
  145: { name: "", location: "", image: "image/level145.png" },
  146: { name: "", location: "", image: "image/level146.png" },
  147: { name: "", location: "", image: "image/level147.png" },
  148: { name: "", location: "", image: "image/level148.png" },
  149: { name: "", location: "", image: "image/level149.png" },
  150: { name: "", location: "", image: "image/level150.png" },
  151: { name: "", location: "", image: "image/level151.png" },
  152: { name: "", location: "", image: "image/level152.png" },
  153: { name: "", location: "", image: "image/level153.png" },
  154: { name: "", location: "", image: "image/level154.png" },
  155: { name: "", location: "", image: "image/level155.png" },
  156: { name: "", location: "", image: "image/level156.png" },
  157: { name: "", location: "", image: "image/level157.png" },
  158: { name: "", location: "", image: "image/level158.png" },
  159: { name: "", location: "", image: "image/level159.png" },
  160: { name: "", location: "", image: "image/level160.png" },
  161: { name: "", location: "", image: "image/level161.png" },
  162: { name: "", location: "", image: "image/level162.png" },
  163: { name: "", location: "", image: "image/level163.png" },
  164: { name: "", location: "", image: "image/level164.png" },
  165: { name: "", location: "", image: "image/level165.png" },
  166: { name: "", location: "", image: "image/level166.png" },
  167: { name: "", location: "", image: "image/level167.png" },
  168: { name: "", location: "", image: "image/level168.png" },
  169: { name: "", location: "", image: "image/level169.png" },
  170: { name: "", location: "", image: "image/level170.png" },
  171: { name: "", location: "", image: "image/level171.png" },
  172: { name: "", location: "", image: "image/level172.png" },
  173: { name: "", location: "", image: "image/level173.png" },
  174: { name: "", location: "", image: "image/level174.png" },
  175: { name: "", location: "", image: "image/level175.png" },
  176: { name: "", location: "", image: "image/level176.png" },
  177: { name: "", location: "", image: "image/level177.png" },
  178: { name: "", location: "", image: "image/level178.png" },
  179: { name: "", location: "", image: "image/level179.png" },
  180: { name: "", location: "", image: "image/level180.png" },
  181: { name: "", location: "", image: "image/level181.png" },
  182: { name: "", location: "", image: "image/level182.png" },
  183: { name: "", location: "", image: "image/level183.png" },
  184: { name: "", location: "", image: "image/level184.png" },
  185: { name: "", location: "", image: "image/level185.png" },
  186: { name: "", location: "", image: "image/level186.png" },
  187: { name: "", location: "", image: "image/level187.png" },
  188: { name: "", location: "", image: "image/level188.png" },
  189: { name: "", location: "", image: "image/level189.png" },
  190: { name: "", location: "", image: "image/level190.png" },
  191: { name: "", location: "", image: "image/level191.png" },
  192: { name: "", location: "", image: "image/level192.png" },
  193: { name: "", location: "", image: "image/level193.png" },
  194: { name: "", location: "", image: "image/level194.png" },
  195: { name: "", location: "", image: "image/level195.png" },
  196: { name: "", location: "", image: "image/level196.png" },
  197: { name: "", location: "", image: "image/level197.png" },
  198: { name: "", location: "", image: "image/level198.png" },
  199: { name: "", location: "", image: "image/level199.png" },
  200: { name: "", location: "", image: "image/level200.png" }
};
